/** Full StayEase amenity catalog — grouped for host listing forms. */

export const AMENITY_CATEGORIES = [
  {
    id: 'internet-connectivity',
    label: 'Internet & Connectivity',
    items: [
      'Wifi',
      'WiFi',
      'Free Wi-Fi',
      'High-speed Wi-Fi',
      'Premium Wi-Fi',
      'Wired internet',
      'Business internet access',
      'Public computer station',
      'Printing services',
      'Ethernet connection',
      'Dedicated workspace',
      'Desk',
      'Office chair',
      'Ergonomic chair',
      'Work desk',
      'Work Desk',
      'Printer',
      'Laptop-friendly workspace',
    ],
  },
  {
    id: 'room-amenities',
    label: 'Room Amenities',
    items: [
      'AC',
      'Air conditioning',
      'Central AC',
      'Portable AC',
      'Heating',
      'Central heating',
      'Ceiling fan',
      'Soundproof rooms',
      'Blackout curtains',
      'Room-darkening shades',
      'Room-darkening blinds',
      'King bed',
      'Queen bed',
      'Twin beds',
      'Sofa bed',
      'Connecting rooms',
      'Balcony',
      'Terrace',
      'Private patio',
      'Patio',
      'Ocean view',
      'Sea view',
      'City view',
      'City skyline view',
      'Mountain view',
      'Garden view',
      'Hill view',
      'Pool view',
      'Smart TV',
      'TV',
      'Cable TV',
      'Streaming services',
      'Netflix',
      'Disney+',
      'Amazon Prime Video',
      'Mini fridge',
      'Refrigerator',
      'Microwave',
      'Kitchenette',
      'Full kitchen',
      'Kitchen',
      'Coffee maker',
      'Tea maker',
      'Electric kettle',
      'Kettle',
      'In-room safe',
      'Safe',
      'Iron',
      'Ironing board',
      'Iron and ironing board',
      'Hair dryer',
      'Bathrobe',
      'Slippers',
      'Jacuzzi tub',
      'Rain shower',
      'Pillow menu',
      'Hypoallergenic bedding',
      'Pillows',
      'Extra pillows',
      'Blankets',
      'Extra blankets',
      'Bed sheets',
      'Bed linen',
      'Crib',
      'Crib available',
      'Travel crib',
      'Rollaway bed',
      'Room service',
      'Room Service',
      '24-hour room service',
      'Minibar',
      'Mini Bar',
      'Walk-in closet',
      'Clothing storage',
      'Hangers',
      'Mosquito net',
    ],
  },
  {
    id: 'bathroom',
    label: 'Bathroom Amenities',
    items: [
      'Private bathroom',
      'Shared bathroom',
      'Shared Bath',
      'Walk-in shower',
      'Shower',
      'Shower chair',
      'Separate bathtub and shower',
      'Towels provided',
      'Towels',
      'Premium toiletries',
      'Luxury toiletries',
      'Shampoo',
      'Conditioner',
      'Body soap',
      'Shower gel',
      'Soap',
      'Toilet paper',
      'Heated towel rack',
      'Makeup mirror',
      'Bidet',
      'Bathtub',
      'Outdoor shower',
      'Hot water',
      'Hot Water',
      'Cleaning products',
    ],
  },
  {
    id: 'essentials',
    label: 'Essentials',
    items: [
      'Housekeeping',
      'Daily housekeeping',
    ],
  },
  {
    id: 'bedroom-laundry',
    label: 'Bedroom & Laundry',
    items: [
      'Washer',
      'Washing machine',
      'Dryer',
      'Free washer',
      'Paid washer',
      'Free dryer',
      'Paid dryer',
      'Laundry service',
      'Dry cleaning',
      'Self-service laundry',
      'Laundry facilities',
      'Express laundry',
      'Turndown service',
      "Children's books and toys",
    ],
  },
  {
    id: 'food-beverage',
    label: 'Food & Beverage',
    items: [
      'Restaurant',
      'Estate Dining',
      'Bar',
      'Lounge',
      'Coffee shop',
      'Café',
      'Rooftop bar',
      'Poolside bar',
      'Complimentary breakfast',
      'Breakfast',
      'Breakfast included',
      'Buffet breakfast',
      'Continental breakfast',
      'Vegan options',
      'Vegetarian options',
      'Halal food',
      'Kosher food',
      'Snack bar',
      'Shared kitchen',
      'BBQ facilities',
      'BBQ grill',
      'Barbecue utensils',
      'Outdoor kitchen',
      'Dining table',
      'Wine glasses',
      'Espresso machine',
      'Toaster',
      'Oven',
      'Stove',
      'Gas stove',
      'Electric stove',
      'Dishwasher',
      'Freezer',
      'Rice maker',
      'Blender',
      'Baking sheet',
      'Pots and pans',
      'Dishes and silverware',
    ],
  },
  {
    id: 'entertainment',
    label: 'Entertainment',
    items: [
      'Game room',
      'Billiards',
      'Pool table',
      'Table tennis',
      'Ping pong table',
      'Bowling',
      'Karaoke',
      'Nightclub',
      'Casino',
      'Cinema/theater',
      'Home theater',
      'Game console',
      'Books',
      'Board games',
      'Piano',
      'Sound system',
      'Projector',
      'DVD player',
    ],
  },
  {
    id: 'wellness-fitness',
    label: 'Wellness & Fitness',
    items: [
      'Gym',
      'Fitness center',
      'Shared gym',
      'Private gym',
      'Exercise equipment',
      'Yoga studio',
      'Personal trainer',
      'Spa',
      'Sauna',
      'Steam room',
      'Hot tub',
      'Jacuzzi',
      'Massage services',
      'Beauty salon',
      'Wellness center',
      'Meditation room',
    ],
  },
  {
    id: 'pool-recreation',
    label: 'Pool & Recreation',
    items: [
      'Pool',
      'Indoor pool',
      'Outdoor pool',
      'Infinity pool',
      'Private pool',
      'Private Pool',
      'Shared pool',
      "Children's pool",
      'Water park',
      'Private beach',
      'Beach access',
      'Beachfront',
      'Beach essentials',
      'Sun loungers',
      'Pool cabanas',
      'Tennis court',
      'Basketball court',
      'Volleyball court',
      'Golf course',
      'Mini golf',
      'Golf simulator',
      'Golf cart',
      'Kayaks',
      'Canoes',
      'Paddle boards',
      'Jet skis',
      'Snorkeling gear',
      'Surfboards',
      'Beach chairs',
      'Private dock',
      'Boat slip',
    ],
  },
  {
    id: 'family',
    label: 'Family-Friendly Amenities',
    items: [
      'Family rooms',
      'Family friendly',
      'High chair',
      "Children's dinnerware",
      'Baby bath',
      'Baby monitor',
      'Changing table',
      'Outlet covers',
      'Fireplace guards',
      'Window guards',
      'Stair gates',
      'Kids club',
      "Children's playground",
      'Babysitting',
      'Childcare services',
      "Children's activities",
      "Children's meals",
      'Baby equipment rental',
    ],
  },
  {
    id: 'business',
    label: 'Business Amenities',
    items: [
      'Business friendly',
      'Business center',
      'Business Centre',
      'Meeting rooms',
      'Conference hall',
      'Banquet hall',
      'Co-working space',
      'Event facilities',
      'Audio/visual equipment',
      'Fax services',
      'Secretarial services',
    ],
  },
  {
    id: 'transportation',
    label: 'Transportation',
    items: [
      'Airport shuttle',
      'Free airport shuttle',
      'Airport transfer',
      'Airport Transfer',
      'Train station shuttle',
      'Cruise port shuttle',
      'Taxi service',
      'Shuttle',
      'Car rental',
      'Bicycle rental',
      'Scooter rental',
      'Valet parking',
      'Free parking',
      'Paid parking',
      'Parking',
      'Garage',
      'Private parking',
      'Accessible parking',
      'EV charger',
      'EV charging station',
    ],
  },
  {
    id: 'heating-cooling',
    label: 'Heating & Cooling',
    items: [
      'Radiant heating',
      'Heated floors',
      'Indoor fireplace',
      'Portable heater',
    ],
  },
  {
    id: 'outdoor',
    label: 'Outdoor',
    items: [
      'Backyard',
      'Garden',
      'Outdoor furniture',
      'Outdoor dining area',
      'Hammock',
      'Fire pit',
      'Rooftop deck',
    ],
  },
  {
    id: 'location-features',
    label: 'Location Features',
    items: [
      'Waterfront',
      'Lake access',
      'Ski-in/ski-out',
    ],
  },
  {
    id: 'accessibility',
    label: 'Accessibility',
    items: [
      'Accessibility features',
      'Wheelchair accessible',
      'Accessible rooms',
      'Accessible bathrooms',
      'Elevator/lift',
      'Lift',
      'Braille signage',
      'Hearing-accessible rooms',
      'Visual alarms',
      'Step-free entrance',
      'Wide doorway',
      'Roll-in shower',
      'Roll-in showers',
      'Grab bars',
      'Accessible-height toilet',
      'Accessible-height bed',
      'Lit path to entrance',
    ],
  },
  {
    id: 'front-desk-services',
    label: 'Front Desk & Guest Services',
    items: [
      '24-hour front desk',
      'Concierge',
      'Express check-in',
      'Express check-out',
      'Mobile check-in',
      'Self check-in kiosk',
      'Self check-in',
      'Keypad entry',
      'Smart lock',
      'Luggage storage',
      'Luggage drop-off allowed',
      'Lockers',
      'Currency exchange',
      'Tour desk',
      'Ticket service',
      'Multilingual staff',
      'Butler service',
      'Butler Service',
      'Wake-up service',
      'Building staff',
      'Host greets you',
      'Cleaning available during stay',
      'Long-term stays allowed',
    ],
  },
  {
    id: 'home-safety',
    label: 'Security & Safety',
    items: [
      'Smoke alarm',
      'Smoke detectors',
      'Carbon monoxide alarm',
      'Fire extinguisher',
      'Fire extinguishers',
      'First aid kit',
      'Security cameras',
      '24-hour security',
      'Security guard',
      'CCTV',
      'Key card access',
      'Lock on bedroom door',
      'Gated property',
      'Emergency medical assistance',
    ],
  },
  {
    id: 'pets',
    label: 'Pet-Friendly Amenities',
    items: [
      'Pets allowed',
      'Pet friendly',
      'Dog-friendly',
      'Cat-friendly',
      'Pet sitting',
      'Pet grooming',
      'Pet beds',
      'Pet bowls',
    ],
  },
  {
    id: 'sustainability',
    label: 'Sustainability Features',
    items: [
      'Solar power',
      'Water-saving systems',
      'Recycling program',
      'Electric vehicle charging',
      'Plastic-free toiletries',
      'Green certification',
      'Energy-efficient lighting',
    ],
  },
  {
    id: 'luxury',
    label: 'Resort & Luxury Amenities',
    items: [
      'Private villas',
      'Helipad',
      'Helicopter transfer',
      'Yacht access',
      'Wine cellar',
      'Cigar lounge',
      'Executive lounge',
      'Club lounge access',
      'Lounge Access',
      'VIP services',
    ],
  },
  {
    id: 'activities',
    label: 'Activities & Experiences',
    items: [
      'Guided tours',
      'Nature Trails',
      'Hiking',
      'Cycling',
      'Snorkeling',
      'Scuba diving',
      'Fishing',
      'Horse riding',
      'Skiing',
      'Snowboarding',
      'Surfing',
      'Kayaking',
      'Cooking classes',
      'Cultural experiences',
      'Wine tasting',
      'Coffee Tasting',
      'Plantation Walk',
      'Bonfire',
      'Campfire',
    ],
  },
];

/** Unique amenity names for validation and flat lists. */
export const AMENITY_LIST = [...new Set(AMENITY_CATEGORIES.flatMap((cat) => cat.items))];

/** Display order for amenity modals (Airbnb-style grouping). */
export const AMENITY_CATEGORY_ORDER = [
  'Bathroom Amenities',
  'Bedroom & Laundry',
  'Room Amenities',
  'Internet & Connectivity',
  'Essentials',
  'Food & Beverage',
  'Kitchen & Dining',
  'Heating & Cooling',
  'Entertainment',
  'Wellness & Fitness',
  'Pool & Recreation',
  'Outdoor',
  'Location Features',
  'Family-Friendly Amenities',
  'Accessibility',
  'Business Amenities',
  'Transportation',
  'Front Desk & Guest Services',
  'Security & Safety',
  'Pet-Friendly Amenities',
  'Sustainability Features',
  'Resort & Luxury Amenities',
  'Activities & Experiences',
  'Useful Booking Features',
  'Other',
];

export function sortAmenityCategories(entries) {
  const rank = new Map(AMENITY_CATEGORY_ORDER.map((label, index) => [label, index]));
  return [...entries].sort(([a], [b]) => (rank.get(a) ?? 999) - (rank.get(b) ?? 999));
}

export function findAmenityCategory(name) {
  return AMENITY_CATEGORIES.find((cat) => cat.items.includes(name))?.label || 'Other';
}
