import {
  Building2,
  Camera,
  Car,
  ChefHat,
  Clapperboard,
  Coffee,
  Dumbbell,
  Film,
  Gamepad2,
  Globe,
  Leaf,
  Music,
  Palette,
  Plane,
  ShoppingBag,
  Sparkles,
  Star,
  TreePine,
  Utensils,
  Waves,
  Wine,
} from 'lucide-react';

const INTEREST_ICONS = {
  Architecture: Building2,
  Coffee: Coffee,
  'Live sports': Dumbbell,
  Chess: Gamepad2,
  Photography: Camera,
  Travel: Plane,
  Wine: Wine,
  Shopping: ShoppingBag,
  Spa: Sparkles,
  Outdoors: TreePine,
  Films: Clapperboard,
  'Food scenes': Utensils,
  'Live music': Music,
  Cars: Car,
  'Building things': Building2,
  'Motor sports': Car,
  'Self-care': Sparkles,
  'Playing music': Music,
  Nature: Leaf,
  Cooking: ChefHat,
  Art: Palette,
  Beach: Waves,
  Culture: Globe,
  Hospitality: Star,
  Movies: Film,
};

export function getInterestIcon(label) {
  return INTEREST_ICONS[label] || Sparkles;
}
